import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, ChefHat, ClipboardList, RefreshCw } from "lucide-react";
import { canteenapi } from "../../api";

export default function CanteenDashboard() {
  const [data, setData] = useState({ total_orders: 0, revenue: 0, demand: [], orders: [] });
  const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); canteenapi.dashboard().then(setData).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const top = data.demand?.[0];
  return <main className="canteen-page"><nav className="app-nav"><Link to="/canteen" className="app-brand"><span>CB</span><strong>CanBook / Canteen</strong></Link><div><Link to="/canteen/orders">Orders</Link><Link to="/canteen/menu">Menu</Link><Link to="/canteen/analytics">Analytics</Link><button onClick={load}><RefreshCw size={15} /></button></div></nav><section className="canteen-hero"><div><div className="eyebrow"><ChefHat size={14} /> KITCHEN CONTROL</div><h1>Good morning.<br /><em>Let's move lunch.</em></h1><p>Today's live demand, revenue and pickup queue at a glance.</p></div><div className="kitchen-live"><span /> Kitchen online</div></section><section className="canteen-stats"><article><span>ORDERS TODAY</span><strong>{loading ? "—" : data.total_orders}</strong><small>excluding cancelled</small></article><article><span>REVENUE</span><strong>AED {Number(data.revenue || 0).toFixed(0)}</strong><small>today so far</small></article><article><span>TOP ITEM</span><strong>{top?.item_name || "—"}</strong><small>{top ? `${top.quantity} ordered` : "No demand yet"}</small></article></section><section className="canteen-grid-modern"><article className="canteen-panel"><header><div><span className="section-kicker">DEMAND</span><h2>What's moving?</h2></div><Link to="/canteen/analytics">Full analytics <ArrowRight size={15} /></Link></header>{data.demand.length ? data.demand.slice(0, 8).map((item, index) => <div className="demand-modern" key={item.item_name}><span>0{index + 1}</span><strong>{item.item_name}</strong><b>{item.quantity}</b></div>) : <div className="empty-state">No orders yet.</div>}</article><article className="canteen-panel"><header><div><span className="section-kicker">QUEUE</span><h2>Recent orders</h2></div><Link to="/canteen/orders">View all <ArrowRight size={15} /></Link></header>{data.orders?.slice(0, 7).map((order) => <div className="queue-modern" key={order.order_id}><div><strong>#{order.order_id}</strong><span>{order.name}</span></div><div><b>{order.status}</b><small>{order.pickup_slot}</small></div></div>)}</article></section></main>;
}
